services:
  sqlserver:
    build:
      context: .
      dockerfile: sqlserver/Dockerfile
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

volumes:
  mssql_data:
  rabbitmq_data:
  rabbitmq_log:
